version: '3.9'

services:
  rabbit:
    image: rabbitmq
    container_name: rabbitmqServer
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  rabbit_core:
    build: ./rabbit_core
    container_name: rabbit_core
    ports:
      - "2137:2137"
    depends_on:
        rabbit:
          condition: service_healthy
  
  rabbit_ai:
    build: ./rabbit_ai
    container_name: rabbit_ai
    ports:
      - "2138:2138"
    depends_on:
      rabbit:
          condition: service_healthy
        
  mongo:
    build: ./mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
volumes:
  mongodb_data:

    
    
